@extends('layouts.app')

@section('title')Головна@endsection

@section('content')
    <div class="container" style="margin-top: 5rem !important;">
    <div class="bd-callout bd-callout-info">
    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio repellendus saepe laboriosam aperiam eius cumque quos recusandae accusantium architecto. Numquam obcaecati assumenda, ipsa blanditiis unde cumque dolores animi nisi veniam possimus quod officia sint ullam molestias, asperiores suscipit! Quod in odio voluptatibus placeat dolore officia fuga vero iste hic magnam doloribus veniam enim quidem tenetur aut repellat cumque minima, ratione incidunt nulla, fugit dicta, eos aperiam labore. Vel similique accusantium nobis quo qui ipsum sed officia exercitationem quam quas, sit eaque itaque, a tempora dignissimos consequatur veritatis molestias laudantium voluptatem aliquam illo nulla aspernatur commodi. Veniam maxime nam doloremque ratione?
    </div>
        <h2>Головна сторінка</h2>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum voluptatum debitis libero dolor ad eum voluptate numquam, quos culpa laboriosam ex omnis saepe, alias quo. Suscipit officiis eum praesentium? Excepturi porro error numquam, reprehenderit sit inventore? Suscipit placeat aliquid dolorem fuga maxime! Earum dolorum et dignissimos quaerat ipsa veniam iusto recusandae aspernatur voluptas, maxime excepturi. Non facere laudantium voluptatem sed porro dolorum veniam. Hic maxime vel deleniti expedita, corrupti iusto explicabo neque quod culpa odio, iste necessitatibus nobis quibusdam quasi ab sunt sit suscipit labore dolorem id tempora distinctio sint! Distinctio molestias nesciunt hic voluptate, facere at, quisquam quae laborum sint quos error nihil aliquam eveniet ad nobis ipsam sunt modi excepturi quo illum labore! Minus culpa porro, officiis esse at earum doloribus dicta dolores quod delectus ut distinctio suscipit numquam! Dolor nam necessitatibus tempora deleniti laboriosam, aut esse expedita accusamus tempore vitae possimus veritatis animi impedit! Omnis accusamus ipsum neque minus autem, placeat, recusandae saepe ad eveniet architecto nostrum ducimus atque ab consequuntur voluptates earum beatae dolorem in molestias doloremque! Sint at iusto quod veniam dolore optio, consequuntur nulla nisi nam repellendus quia, et fugit vero. Exercitationem, inventore earum. Dolorem impedit alias, quia debitis nesciunt eaque. Modi, quo. Cum nemo corrupti excepturi architecto ab. Repellat omnis ducimus iure nihil, nemo in aliquam eos mollitia, obcaecati possimus rem atque eius voluptatem dolorem quidem velit ex, a consequuntur quos unde vitae? Assumenda vero error voluptate recusandae suscipit id fugiat. Dolorum nisi optio ea ad at fugit deleniti quas repellendus doloribus, veritatis, libero similique facere eaque placeat sunt consectetur facilis possimus accusantium pariatur molestiae quibusdam impedit dolores. Iste assumenda nostrum nam aliquid, autem perferendis iusto odit quaerat neque reiciendis deleniti saepe nemo voluptatem enim? Porro doloribus reprehenderit ex nesciunt veniam voluptatum maxime, dicta temporibus magnam velit. Molestias dolorem nostrum quia earum voluptas?
    </div>   
@endsection